- name: Install rpm
  dnf:
    name: 'https://rpms.remirepo.net/enterprise/remi-release-8.rpm'
    state: present
    disable_gpg_check: yes

- name: Enable remi repo
  shell: dnf module enable -y redis:remi-6.0

- name: Insall Redis
  include_tasks: installredis.yml

- name: check dir
  include_tasks: checkdir.yml
  vars:
    folder: "/etc/redis"

- name: Remove default redis service
  ignore_errors: yes
  shell: |
    systemctl disable redis 

- name: Delete redis service
  ignore_errors: yes
  file: 
    path: "{{ item }}"
    state: absent
  with_items: 
    - /usr/lib/systemd/system/redis.service
    - /etc/systemd/system/redis.service.d
    - /etc/systemd/system/redis-sentinel.service.d

- name: Disable SELinux
  shell: |
    setenforce 0
    sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

- name: Allow Overcommit Memory
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: yes
    ignoreerrors: yes

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False
